### ISSUE TITLE
Android集成提示Failed resolution of: Landroid/support/v4/content/ContextCompat;

### ISSUE THREAD

**Issue by hekaiyou** [OpenFlutter/nautilus#4]
E/AndroidRuntime(27672): FATAL EXCEPTION: SDK Looper Thread
E/AndroidRuntime(27672): Process: com.hekaiyou.jedi, PID: 27672
E/AndroidRuntime(27672): java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/ContextCompat;
E/AndroidRuntime(27672): 	at com.alimama.tunion.utils.TUnionPhoneInfoUtils.<init>(TUnionPhoneInfoUtils.java:154)
E/AndroidRuntime(27672): 	at com.alimama.tunion.utils.TUnionPhoneInfoUtils.getInstance(TUnionPhoneInfoUtils.java:48)
E/AndroidRuntime(27672): 	at com.alimama.tunion.trade.net.TUnionNetworkRequest.a(TUnionNetworkRequest.java:76)
E/AndroidRuntime(27672): 	at com.alimama.tunion.trade.net.TUnionNetworkRequest.createABTestRequest(TUnionNetworkRequest.java:113)
E/AndroidRuntime(27672): 	at com.alimama.tunion.trade.abtest.TUnionABTestService.a(TUnionABTestService.java:184)
E/AndroidRuntime(27672): 	at com.alimama.tunion.trade.abtest.TUnionABTestService.b(TUnionABTestService.java:238)
E/AndroidRuntime(27672): 	at com.alimama.tunion.trade.abtest.TUnionABTestService.startInitialFetch(TUnionABTestService.java:244)
E/AndroidRuntime(27672): 	at com.alimama.tunion.trade.TUnionTradeSDK.register(TUnionTradeSDK.java:151)
E/AndroidRuntime(27672): 	at com.alibaba.baichuan.trade.biz.core.taoke.AlibcAidCompoment.init(Unknown Source)
E/AndroidRuntime(27672): 	at com.alibaba.baichuan.trade.biz.AlibcMiniTradeBiz.init(Unknown Source)
E/AndroidRuntime(27672): 	at com.alibaba.baichuan.trade.biz.AlibcTradeBiz.init(Unknown Source)
E/AndroidRuntime(27672): 	at com.alibaba.baichuan.android.trade.AlibcTradeSDK.b(Unknown Source)
E/AndroidRuntime(27672): 	at com.alibaba.baichuan.android.trade.AlibcTradeSDK.a(Unknown Source)
E/AndroidRuntime(27672): 	at com.alibaba.baichuan.android.trade.f.run(Unknown Source)
E/AndroidRuntime(27672): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime(27672): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(27672): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(27672): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/AndroidRuntime(27672): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.ContextCompat" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.hekaiyou.jedi-2/base.apk"],nativeLibraryDirectories=[/data/app/com.hekaiyou.jedi-2/lib/x86, /data/app/com.hekaiyou.jedi-2/base.apk!/lib/x86, /system/lib, /vendor/lib]]
E/AndroidRuntime(27672): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(27672): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
E/AndroidRuntime(27672): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(27672): 	... 18 more

**Comment by hekaiyou** [comment]
解决勒，因为我同时用了极光推送的插件，而极光用了androidx.appcompat，问题就是这个androidx，它和android.support不兼容，所以androidx.appcompat、android.support只能存在一个。参考[AndroidX升级日记](https://www.jianshu.com/p/55645eb89214)把项目里面的所有android.support换成androidx.appcompat。就解决了
